### PR TITLE
Forward attributes on `impl` function parameters to variable declaration.

### LINKED ISSUE #226: Attributes on impl parameters are not forwarded to body
Heya, I was implementing a trait function with `#[cfg(..)]` in its parameters, and encountered the following error:

```rust
// within trait impl
async fn cfg_param(
    &self,
    #[cfg(not(feature = "something"))] param: u8,
    #[cfg(feature = "something")] _unused: u8,
    //                            ^^^^^^^
    // cannot find value `_unused` in this scope
) -> u8 {
    #[cfg(not(feature = "something"))]
    { param }
    #[cfg(feature = "something")]
    { 1 }
}
```

The expanded code body shows:

```rust
let __self = self;
let param = param;
let _unused = _unused;
let __ret: u8 = { #[cfg(not(feature = "something"))] { param } };
#[allow(unreachable_code)] __ret
```

Since `_unused` is not present in the function signature, the expanded code should likely just omit it.

#227 forwards the attributes, such that the expanded code returns:

```rust
let __self = self;
#[cfg(not(feature = "something"))]
let param = param;
let __ret: u8 = { #[cfg(not(feature = "something"))] { param } };
#[allow(unreachable_code)] __ret
```

The `_unused` statement isn't present since it's been removed by the expansion.

### PR DESCRIPTION
**Pull request by azriel91**
Fixes #226.

It feels rare to have attributes on parameters, I can't imagine a concrete scenario where forwarding all attributes is undesirable.
We could filter the attributes that are forwarded to only the `#[cfg(..)]` ones.

### CODE REVIEW

File: src/expand.rs [hunk 1]
```diff
@@ -371,7 +371,13 @@ fn transform_block(context: Context, sig: &mut Signature, block: &mut Block) {
...
+                        // If there is a `#[cfg(..)]` attribute that selectively
+                        // enables the parameter, forward it to the variable.
+                        let attrs = arg.attrs.iter();
+                        quote!(
+                            #(#attrs)*
+                            let #mutability #ident = #ident;
+                        )
                     }
                 } else {
                     let pat = &arg.pat;
```
Comment (azriel91) [inline src/expand.rs:383]: I'm not sure how to hit this branch -- I tried using a `DeconstructedStruct { value }` but it didn't parse.

Presumably the same attribute forwarding needs to be done here as well

Comment (dtolnay) [reply src/expand.rs:383]: Try `#[cfg(any())] _: T` or `#[cfg(any())] (a, b): (T, T)`

Comment (azriel91) [reply src/expand.rs:386]: cool thanks, managed to simplify the test case

**Review by dtolnay — APPROVED** [review]
Thanks!
