### PR TITLE
Transform blocks into `async move` for more compatibility

### LINKED ISSUE #126: default impl for methods with `impl trait` arguments?
Given the code:
```
use async_trait::async_trait; // 0.1.36
use tokio; // 0.2.21

#[async_trait]
trait MyTrait {
    async fn blah(&self, values: impl Iterator<Item = i32> + Send + 'async_trait) {
        println!("this is the default");
    }
}

struct S;

#[async_trait]
impl MyTrait for S {
    async fn blah(&self, values: impl Iterator<Item = i32> + Send + 'async_trait) {
        for value in values {
            println!("{}", value);
        }
    }
}

#[tokio::main]
async fn main() {
    let s = S;
    s.blah([1, 2, 3].iter().cloned()).await;
}
```

this fails to compile with the error:
```
error[E0632]: cannot provide explicit generic arguments when `impl Trait` is used in argument position
 --> src/main.rs:4:1
  |
4 | #[async_trait]
  | ^^^^^^^^^^^^^^ explicit generic argument not allowed
  |
  = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

If I remove the default body, it works.

Is this intended to be supported? I can work around it by boxing and using `dyn`, i.e. `values:  Box<dyn Iterator<Item=i32> + Send + 'async_trait>` but that's not ideal.

Thanks for this crate!

### PR DESCRIPTION
**Pull request by SergioBenitez**
This is effectively #125 with correct drop ordering. I've kept the changes minimal, hence the temporary `allow(dead_code, unused_imports)`, which will be removed once this is approved and I sweep out the now-unused code.

This breaks #45/#97, which from a cursory reading, looks like is a result of hard-coding previous functionality into `tracing`, though do let me know if there's something I can do here to maintain that compatibility.

I should add: this makes quite a few more `impl`s in Rocket compile without needing to manually expand the async-trait or other hackery. This fixes all of the cases related to #61 in Rocket. My guess, though I haven't tested, is that this fixes #126 as well.

### CODE REVIEW

**Comment by SergioBenitez** [comment]
cc @nightmared @hawkw re: #45/#97

**Review by dtolnay — COMMENTED** [review]
Thanks, this is great. I am on board with this if we can get the regression rate low. Luckily I have a work codebase with thousands of uses of #\[async_trait\]. A significant fraction of them are broken by this PR, so I will get started on triaging those.

**Comment by SergioBenitez** [comment]
> A significant fraction of them are broken by this PR, so I will get started on triaging those.

Awesome! Let me know if I can help with triaging some of those!

File: src/expand.rs [hunk 1]
```diff
@@ -247,247 +251,67 @@ fn transform_sig(
...
-//     async fn f<T, AsyncTrait>(_self: &AsyncTrait, x: &T) -> Ret {
-//         _self + x
-//     }
-//     Box::pin(async_trait_method::<T, Self>(self, x))
+//     Box::pin(async move {
+//         let __self = self;
+//         let x = x;
+//         let (a, b) = __arg1;
+//
+//         __self + x
```
Comment (SergioBenitez) [inline src/expand.rs:264]:
```suggestion
//         __self + x + a + b
```

**Comment by dtolnay** [comment]
A lot of things that use `self` more than once in a function fail with "borrow of moved value". Something like:

```rust
use async_trait::async_trait;

#[async_trait]
trait Trait {
    async fn f(self);
}

#[async_trait]
impl Trait for String {
    async fn f(self) {  // same for &mut self
        println!("{} {}", self, self);
    }
}
```

```console
error[E0382]: borrow of moved value: `self`
  --> src/main.rs:11:27
   |
10 |     async fn f(self) {
   |                ---- value moved here
11 |         println!("{} {}", self, self);
   |                           ^^^^ value borrowed here after move
   |
   = note: move occurs because `self` has type `String`, which does not implement the `Copy` trait
```

**Comment by SergioBenitez** [comment]
Ah, that one's easy. So the `SelfRenamer` visitor only looks at `Ident`s to rename all `self` to `__self`; the `self` there are arbitrary tokens in the macro call's token stream, so they're missed by the renamer.

We _could_ visit the tokens in the token stream and rename those `self`'s too.

Alas, I'd hope there was something more clever we could do with `self`. It's a real bummer to rename `self` to `__self` and then have to rename every other `self` in the block.

**Comment by SergioBenitez** [comment]
> We _could_ visit the tokens in the token stream and rename those `self`'s too.

Now that I take a closer look at your original implementation, I see that this is exactly what you used to do.

**Comment by dtolnay** [comment]
Here is a "type mismatch" failure that appears to be quite common:

```rust
use async_trait::async_trait;

#[async_trait]
pub trait Trait {
    async fn f() -> Box<dyn Stream<Item = ()>> {
        Box::new(Iter(std::iter::empty()))
    }
}

pub struct Iter<I>(I);

pub trait Stream {
    type Item;
}

impl<I: Iterator> Stream for Iter<I> {
    type Item = I::Item;
}
```

```console
error[E0271]: type mismatch resolving `<impl Future as Future>::Output == Box<(dyn Stream<Item = ()> + 'static)>`
 --> src/main.rs:5:48
  |
5 |       async fn f() -> Box<dyn Stream<Item = ()>> {
  |  ________________________________________________^
6 | |         Box::new(Iter(std::iter::empty()))
7 | |     }
  | |_____^ expected trait object `dyn Stream`, found struct `Iter`
  |
  = note: expected struct `Box<(dyn Stream<Item = ()> + 'static)>`
             found struct `Box<Iter<std::iter::Empty<_>>>`
  = note: required for the cast to the object type `dyn Future<Output = Box<(dyn Stream<Item = ()> + 'static)>> + Send`
```

**Comment by dtolnay** [comment]
I think those are the big two. Will check again after those are fixed. There is a third category which is some logging-related proc macros doing something tracing-like on the inner code but we can get that fixed to recognize `Box::pin(async move {...})`. As far as I can tell all the failures involve one of these three: `self` in a macro argument, trait object in return type, or hacky proc macro which is fine to break.

**Comment by dtolnay** [comment]
One more thing: this regresses #105 on compilers 1.46 and older, which is this failure in the 1.40 CI job:

```console
error[E0425]: cannot find value `__self` in this scope
   --> tests/test.rs:599:13
    |
599 |             #[async_trait]
    |             ^^^^^^^^^^^^^^ not found in this scope
```

If it's easy, it would be good to get that worked around again even if new rustc fixed the bug. It was only a 1 line workaround in #105.

**Comment by nightmared** [comment]
I'll take a look at this. I guess the proper course of action would be to support both the old and the new behavior ?
if so, looks like we need to do some working on tracing-attributes :p

**Comment by dtolnay** [comment]
I tried the latest commit -- it's regressing some code like this:

```rust
use async_trait::async_trait;

#[async_trait]
pub trait Trait: Sized {
    async fn f(self) {
        struct Struct;
        impl Struct {
            fn f(self) {
                let _ = self;
            }
        }
    }
}
```

```console
error[E0434]: can't capture dynamic environment in a fn item
 --> src/main.rs:9:25
  |
9 |                 let _ = self;
  |                         ^^^^
  |
  = help: use the `|| { ... }` closure form instead
```

**Comment by dtolnay** [comment]
Also this:

```rust
#![deny(warnings)]

use async_trait::async_trait;

#[async_trait]
pub trait Trait {
    async fn f() {
        unimplemented!()
    }
}
```

```console
error: unreachable expression
 --> src/main.rs:7:18
  |
7 |       async fn f() {
  |  __________________^
8 | |         unimplemented!()
  | |         ---------------- any code following this expression is unreachable
9 | |     }
  | |_____^ unreachable expression
```

**Comment by SergioBenitez** [comment]
Alright, that last commit should handle all of the regressions thus far. As a side effect, some error messages have improved. Feel free to hit me with more regressions.

I've also marked the `tracing` test `should_panic` for now.

**Comment by SergioBenitez** [comment]
Oh, perhaps I missed the point of the unreachable example you showed. I see the deny warnings now. Makes sense. Will take a look a bit later.

File: tests/ui/self-span.stderr [hunk 2]
```diff
@@ -1,27 +1,24 @@
...
-  --> $DIR/self-span.rs:25:21
+  --> $DIR/self-span.rs:24:21
    |
+24 |     async fn method(self) {
+   |                     ^^^^ expected `()`, found enum `E`
 25 |         let _: () = self;
-   |                --   ^^^^ expected `()`, found enum `E`
-   |                |
-   |                expected due to this
+   |                -- expected due to this
```
Comment (dtolnay) [inline tests/ui/self-span.stderr:21]: Do you have any insight into what's going on with this error message? The error before this PR is what I would expect and matches what you get in the non-trait case: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f8833ba4ae1fad764bbaa11f1f6f2701. The error after seems misplaced to me.

**Review by dtolnay — COMMENTED** [review]
This looks good to me.

I'll give a little time before merging to give the `tracing` folks a chance to get an update out.

**Comment by SergioBenitez** [comment]
> This looks good to me.
> 
> 
> 
> I'll give a little time before merging to give the `tracing` folks a chance to get an update out.

Awesome. I'll remove all of the unused code then.

File: tests/ui/self-span.stderr (hunk 2 above)
Comment (SergioBenitez) [reply tests/ui/self-span.stderr:21]: Ah, interesting. I had read this message differently and believed it to be an improved version of the previous one, but I see now what the intention of the message is and how this is now a bit more confusing.

The span for that second `self`, which is renamed to `__self`, is set to the span of the receiver to fix #105. Besides being able to change only the resolution context, I'm not sure what heuristic to apply here to change only affected `self`s.

Comment (SergioBenitez) [reply tests/ui/self-span.stderr:21]: I'm really not sure what to do here. The previous workaround seemed to "work" because we generated a new function. Now that we don't do so, we need to replace the span of all `self`s, not just of the one argument to the function as before. This will result in all error messages that correspond to `self` to point to the receiver, which is an unfortunate compromise.

My suggestion is that we gate this workaround to rustc versions <= 1.45, or whenever the fix landed in the compiler.

Comment (dtolnay) [reply tests/ui/self-span.stderr:21]: Sounds good, let's do that. Thanks!

Comment (SergioBenitez) [reply tests/ui/self-span.stderr:21]: Have a preference for library to use? My go-to is versioncheck.

**Comment by nightmared** [comment]
On some minor note, it is not so easy to handle arguments that aren't used inside the function: https://github.com/tokio-rs/tracing/pull/1228#issuecomment-774549503.
From what I could gather, `async-trait` redefines the variable `v` with a let binding, but in the process of doing so, it introduces an unused variable.
If I'm not mistaken, the logic is the following:
a) `async_trait` rewrites the body of `async fn call(&mut self, v: usize) {}` in this fashion:
```rust
Box::pin(async move {
  let __ret: () = {
      let mut __self = self;
      let v = v;
  };
  #[allow(unreachable_code)]
  __ret
})
```
So far, it have the same behavior as an equivalent sync function would have, so the warning is expected, and thus not an issue.
b) `instrument` then rewrites the body as:
```rust
Box::pin(async move {
  XXX // something that uses the `v` variable
  tracing::Instrument::instrument(
      async move {
          {
              let __ret: () = {
                  let mut __self = self;
                  let v = v;
              };
              #[allow(unreachable_code)]
          __ret
        }
      },
      __tracing_attr_span,
    )
    .await
})
```
In that case, the `v` variable is now used by code originated from tracing, but there is still the `let v = v;` binding, which is still an unused variable. Because they have the same span, the compiler reports the error as originating from the function signature:
```
warning: unused variable: `v`
   --> tracing-attributes/tests/async_fn.rs:176:34
    |
176 |         async fn call(&mut self, v: usize) {}
    |                                  ^ help: if this is intentional, prefix it with an underscore: `_v`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted
```

I'm not really sure about the way to go here. Optimally, we would inject `instrument` code after `async-trait`, but I don't think we can force ordering (or this whole story of async-trait/tracing integration would never have been a real deal) of procedural macros.
Any idea?

**Comment by dtolnay** [comment]
@nightmared, would it help if we insert some unique distinguishing marker like `let __async_trait: ();` in between the `let` statements and the user's original function body?

```rust
Box::pin(async move {
    let __ret: #RETURN = {
        let v = v;
        let __async_trait: ();
        #BODY
    };
    #[allow(unreachable_code)]
    __ret
})
```

You could crawl the macro input and replace that marker with:

```rust
Box::pin(async move {
    let __ret: #RETURN = {
        let v = v;
        if false {
            let _ = &(v + 5);  // expr from #[instrument(fields(test=%v+5))]
        }
        #BODY
    };
    #[allow(unreachable_code)]
    __ret
})
```

**Comment by nightmared** [comment]
Hmm yes, i guess this would work! However that also means we would have to follow variable reassignments like `self` being renamed to `__self`. Given I'm not really the one that will bear the burden of maintaining that compatibility in the long run (not being a maintainer, nor even an active contributor :p), I guess the best is to defer that decision to e.g. @hawkw and/or @davidbarsky.
That being said, it would probably be the cleanest way to properly place the code generated by `#[instrument]`, and solve this issue altogether. It's probably fairly easy too: we would just have to wrap all the statements from the position of `__async_trait` to the end of the block.

**Comment by nightmared** [comment]
I have started to take a look at @dtolnay's solution, but it isn't quite as trivial as I first thought because we need to keep track of variable reassignments (e.g. `let __self = self`). I will keep you posted on my progress.

**Comment by SergioBenitez** [comment]
To propose a different solution: what if nothing is done about the warning? The warning _feels_ correct to me: the variable is declared and never used in the function body by the written code. Purposefully silencing this warning could result in incorrect code that otherwise would have been caught. It's also easy enough to add an `_` should they really intend not to use the variable.

**Comment by nightmared** [comment]
That is a possibility yes. However with some very minimal changes in async-trait (https://github.com/nightmared/async-trait/commit/32b1573a9d237ad3b277f20645e85711c0838cd7) and a bit more work on tracing side, I was able to get this minor nitpick working ;)
We'll see what the maintainers of tracing think of this hack.

**Comment by SergioBenitez** [comment]
@dtolnay I'm continuing to work to improve `async-trait` in my local branch. When you're ready to merge this, let me know if you'd prefer squashing into fewer commits and/or multiple PRs.

**Comment by Kiiyya** [comment]
I am getting rather odd build errors with a minimal project with commit 0cda89b somehow:
```rust
#[async_trait::async_trait]
pub trait Derp {
    async fn hi();
}
```
fails to build with internal errors, both latest stable and nightly. Note that I literally just have those 4 lines + a dummy `main()`: https://gist.github.com/Kiiyya/250dc864682cc1fc256f6ac6135db45e And I have no clue what is going on, but I thought I'd just drop this here in hopes it helps, somehow?

For some reason, using that exact same commit in a way bigger project of mine compiles, I am properly confused about that elusive build error.

**Comment by SergioBenitez** [comment]
@Kiiyya Your larger project is probably enabling features of `syn` that result in `Debug` being implemented on those types while `async-trait` doesn't enable such features. This is was an omission on my part ... to omit the `Debug` derive. I've pushed a commit that should resolve the issue! Thanks for testing.

**Comment by Kiiyya** [comment]
Yep works now, that was quick, thank you!

File: src/expand.rs [hunk 3]
```diff
@@ -247,247 +268,86 @@ fn transform_sig(
...
-    let consts = standalone
-        .generics
-        .const_params()
-        .map(|param| param.ident.clone());
-    generics.extend(consts);
+    let box_pin = quote_spanned!(ret_ty.span()=>
+        Box::pin(async move {
+            let __ret: #ret_ty = {
+                #(#decls)*
+                #(#stmts)*
```
Comment (nightmared) [inline src/expand.rs:338]: In order for https://github.com/tokio-rs/tracing/pull/1228 to work well, could you consider adding `let __async_trait: ();` between the `#(#decls)*` and `#(#stmts)*` lines? That should do the job. Thanks!

Comment (SergioBenitez) [reply src/expand.rs:338]: I think this is a poor solution to the problem at hand, and that emitting warnings is, in fact, the desired effect. Nevertheless, I've pushed a commit that implements this.

Comment (nightmared) [reply src/expand.rs:341]: I do agree that it's a hack, and a nasty one at that. On the other hand, I do not believe that users will understand that exhibit A will trigger a warning and not exhibit B. That doesn't appear very coherent (at least with what I think is the behavior of `instrument` in non-async-trait functions) either.

Exhibit A:
```rust
#[instrument(fields(test=%v+5))]
async fn call(&mut self, v: usize) {}
```

Exhibit B:
```rust
#[instrument(fields(test=%_v+5))]
async fn call(&mut self, _v: usize) {}
```

Comment (SergioBenitez) [reply src/expand.rs:341]: I disagree that users won't undestand. Without the attribute, `A` triggers a warning and `B` does not because `v` is unused in the body of `A`. Even when the attribute is applied, `v` continues to be unused in `A`, and so it is my opinion that `A` should continue to result in a warning.

I don't mean to imply that `instrument` should inconsistently emit warnings based on whether `async-trait` is used, but instead, that it should consistently emit warnings as would be emitted without the attribute.

**Review by dtolnay — APPROVED** [review]
Thanks, this is great.

**Comment by dtolnay** [comment]
I ended up landing this without the workaround for tracing-attributes because https://github.com/dtolnay/async-trait/pull/143#issuecomment-777964508 / https://github.com/dtolnay/async-trait/pull/143#discussion_r583208853 are compelling to me.
