### PR TITLE
Fix `clippy::shadow_same` warning

### LINKED ISSUE #183: `clippy::shadow_same` is triggered due to duplicated variable names
```rust
#![deny(clippy::shadow_same)]

#[async_trait::async_trait]
trait Foo {
    async fn foo(_n: i32) {}
}

```

### PR DESCRIPTION
**Pull request by c410-f3r**
Fix #183

### CODE REVIEW

File: tests/test.rs [hunk 1]
```diff
@@ -1377,3 +1377,13 @@ pub mod issue169 {
...
+
+// https://github.com/dtolnay/async-trait/issues/183
+pub mod issue183 {
+    #![deny(clippy::shadow_same)]
+
+    #[async_trait::async_trait]
+    trait Foo {
+        async fn foo(_n: i32) {}
+    }
+}
```
Comment (dtolnay) [inline tests/test.rs]:
```suggestion
}
```

**Review by dtolnay — APPROVED** [review]
Thanks!
